### ISSUE TITLE
Issue with vector keys

### ISSUE THREAD

**Issue by mcmahanp** [scheinerman/Counters.jl#1]
I'm having an issue using vectors as keys for Counter objects. I can assign keys and increment values just fine, but trying to access values specifically, it seems to be trying to access some elements of the keys as values, causing problems.

A simple reproducible example:

```{julialang}
using Counters

c = Counter{Vector{String}}()
c[["a","bc"]] += 10
c[["a","bc","def"]] += 100

# prints values "bc" and "bc" instead of 10 and 10
values(c)


c[["a"]] += 1

# raises a BoundsError
values(c)
```

julia version 1.8.3
Counters v0.2.1

**Comment by scheinerman** [comment]
`Counters` is now at version 0.3.3. I tried your example on my computer and the errors didn't occur.

**Comment by mcmahanp** [comment]
Oh sorry, my mistake! I thought I had the latest version.
